/** Organisation role catalogue, supplied to the model as grounding for role-fit analysis. */
export const ROLES_DATA = `Division,Department,Role,Responsibilities
Business Excellence,N/A,Head of Business Excellence,"Strategic Planning and Execution: • Develop and implement a comprehensive strategy that aligns with the Organization’s Goals • Identify key areas for improvement across the organization and prioritize initiatives that will have the greatest impact on operational efficiency and business performance. Process Improvement and Optimization: • Lead the team of Process Improvement Managers in identification, analysis, and redesign of business processes."
Business Excellence,People and Growth (BizEx),AI Vanguard,"1. Spend time with different Employees to understand how work methods can be improved using AI tools, Stride or any other Tech oriented solution. As per need, conduct research, identify best solution and train the user. 2. Facilitate BizEx team members in projects that require UI UX designing  3. Collaborate with Software Vendors for AI related Projects."
Finance,Financial Planning and Reporting,Head of Financial Planning and Reporting,"Regular: Compliance and Reporting: • Ensures compliance with local and international financial regulations and standards and oversees the preparation and dissemination of accurate financial reports to stakeholders. Investment and Capital Management: • Manages the company's CAPEX and financing strategies to optimize financial performance and enhance shareholder value."
Finance,Treasury and Transactional Finance,Head of Treasury and Transactional Finance,"Regular: Cash Management: • Oversee the company's cash management strategies, including cash flow forecasting, liquidity management, and maintaining strong banking relationships. Risk Management: • Identify financial risks and develop strategies to mitigate them. Debt Management: • Oversee the company's debt portfolio."
Human Resource,Talent Acquisition,Head of Talent,"Talent Acquisition Strategy: • Design and execute innovative talent acquisition strategies to attract and retain top talent. Employer Branding: • Strengthen the company's employer brand. Recruitment & Selection: • Oversee the entire recruitment process. Performance Management: • Facilitate Departments in setting up SMART objectives. Succession Planning: • Implement a strategic succession planning process."
Human Resource,HR Ops,Head of HR Ops,"1. HR Operations and Process Optimization: Oversee day-to-day HR operations. 2. HR Policies and Compliance: Develop and implement HR policies. 3. Employee Welfare: Administer wellness programs. 4. Grievance Handling: Resolve conflicts. 5. HR Analytics: Analyze HR data. 6. Budgeting: Design annual budget."
Information Technology,IT Infrastructure,IT Infrastructure Manager,"• VM Management • Network Management • Storage Management • Physical Server Management • Firewall Management • Server, Network and Firewall Management Reporting • Compliance of IT Policies • User Data Backup Management • Infrastructure Vendor Management • Email Server Management"
Information Technology,IT Support,IT Support Manager,"• Support Vendor Management • User Email Access Management • Assets Management and Planning • Windows Upgrade and Antivirus Management Planning • Preventive Maintenance Planning • Attendance Machines Management • Access Control Devices Management • Ensuring Compliance of IT Policy and SOPs"
International Marketing,Global Trade and Market Development,Market Development Manager,"New Market Development: • Identify, evaluate, and develop new market opportunities. Strategy Development: • Develop comprehensive market development strategies. Cross-Functional Collaboration: • Work with Sales, Marketing, Regulatory Affairs, Supply chain and BD teams. Reporting and Analytics: • Utilize analytical tools to present data-driven insights."
Plant Operations,Production,Head of Production,"Strategic Leadership: • Develop and implement strategic plans for production operations. Operational Management: • Oversee all aspects of production operations. Resource Management: • Manage production resources. Quality Assurance: • Coordinate with Quality Operations. Continuous Improvement: • Lead continuous improvement initiatives. Safety and Environmental Compliance: • Ensure compliance with EHS regulations."
Plant Operations,Engineering and EHS,Head of Engineering,"• Ensuring the availability of production and utility facilities. • Organization of the department including selection of staff. • Interpret all management policies to the organization. • Selection and control of vendors and contactors. • Project management including specification, estimation, execution. • Oversee maintenance requirements to optimize efficiency."
Plant Operations,Admin and IR,Admin Manager,"1. Industrial Relations (IR) Management: Develop and implement strategic IR plans. 2. Administrative Management: Oversee overall administrative operations. 3. Third Party Management: Enforce company policies for security and assets. 4. Legal & Regulatory Compliance: Ensure full compliance with labor laws. 5. Risk Management: Identify and assess potential risks. 6. Training & Development: Oversee training programs."
Quality Operations,Quality Assurance,Head of Quality Assurance,"Leadership and Team Development: • Lead and manage the QA team. Regulatory Compliance: • Ensure compliance with PIC/s, DRAP guidelines. Internal and External Audits: • Plan and conduct audits. In-Process Quality Control: • Oversee in-process quality control. Quality Policies: • Develop and maintain quality policies. Risk Management: • Conduct risk assessments. Vendor Qualification: • Ensure effective vendor qualification."
Quality Operations,Quality Control,Head of Quality Control,"Quality Control Planning: • Develop and implement QC plans. Product Testing: • Oversee testing and release of goods. Microbiology: • Manage microbiology testing activities. Raw Material Testing: • Supervise testing of raw materials. Method Validation: • Develop and validate QC testing methods. Continuous Improvement: • Lead continuous improvement initiatives."
Pharma Development and Affairs,Business Development,Business Development Manager,"New Product Development: • Conceptualize, plan, and execute initiatives to develop innovative products. Sales Support and Growth: • Providing sales support through strategic planning. Market Analysis: • Conducting comprehensive market research. Team Leadership: • Fostering team cohesion. Cross-Functional Collaboration: • Collaborate with diverse teams."
`;
